### ISSUE TITLE
Issues on appendix

### ISSUE THREAD

**Issue by banix178** [geyanqi/SAR#3]
I didn't find something about long-tailed classification. Looking forward to your further instruction.

**Comment by geyanqi** [comment]
Hi, banix. The implementation of the classification task is almost the same as that of the segmentation task. The only difference is that each image in segmentation requires p2a loss for each pixel, while the classification task only requires p2a loss for each image.

Since my server is currently down, I can't provide you with the code at the moment. I will provide you with a simple implementation of classifier after the server startup.

**Comment by banix178** [comment]
Thanks for your reply.

**Comment by geyanqi** [comment]
hi guys, this is an implementation example of SAR on the classification task. 

[Link](https://gist.github.com/geyanqi/2a8c6caac433aab76f85a330cd994d26/edit)
